name: dev-env-init
on: [push]

env:
  PACKAGE_TESTING_REPO_URL: https://github.com/bricksflow/databricks-bundle.git
  PACKAGE_TESTING_REPO_DIR: databricks-bundle
  APP_TESTING_REPO_URL: https://github.com/bricksflow/bricksflow.git
  APP_TESTING_REPO_DIR: bricksflow

jobs:
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'bricksflow/databricks-bundle'
          path: 'databricks-bundle'
      - name: Init
        run: |
          echo "************ Installing Conda ************"
          wget --quiet -O Miniconda3-latest-Linux-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
          chmod +x Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          source ~/miniconda/etc/profile.d/conda.sh
          echo "****** Setting up Conda environment ******"
          cd $PACKAGE_TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          echo "******* 2nd env-init.sh invocation *******"
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          ./run_tests.sh
          echo "********* .bashrc modifications **********"
          if ! grep -q "pyfony_env.sh" "$HOME/.bashrc"; then
              echo "pyfony_env.sh was not added to .bashrc"
              exit 1
          fi
          if [[ ! -f "$HOME/pyfony_env.sh" ]]; then
              echo "pyfony_env.sh was not created"
              exit 1
          fi
  app-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'bricksflow/bricksflow'
          path: 'bricksflow'
      - name: Init
        run: |
          echo "************ Installing Conda ************"
          wget --quiet -O Miniconda3-latest-Linux-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
          chmod +x Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          source ~/miniconda/etc/profile.d/conda.sh
          echo "****** Setting up Conda environment ******"
          cd $APP_TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          echo "******* 2nd env-init.sh invocation *******"
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          ./run_tests.sh
          echo "********* .bashrc modifications **********"
          if ! grep -q "pyfony_env.sh" "$HOME/.bashrc"; then
              echo "pyfony_env.sh was not added to .bashrc"
              exit 1
          fi
          if [[ ! -f "$HOME/pyfony_env.sh" ]]; then
              echo "pyfony_env.sh was not created"
              exit 1
          fi

  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'bricksflow/databricks-bundle'
          path: 'databricks-bundle'
      - name: Conda installation
        run: |
          powershell -Command "Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Windows-x86_64.exe -OutFile Miniconda3-latest-Windows-x86_64.exe"
          start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /AddToPath=1 /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
        shell: cmd
      - name: Init
        run: |
          echo "************ Setting up Conda ************"
          source ~/Miniconda3/etc/profile.d/conda.sh
          PATH=$HOME/Miniconda3/Scripts:$PATH
          echo "****** Setting up Conda environment ******"
          cd $PACKAGE_TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          echo "******* 2nd env-init.sh invocation *******"
          PATH=$HOME/.poetry/bin:$PATH
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          ./run_tests.sh
          echo "********* .bashrc modifications **********"
          if ! grep -q "pyfony_env.sh" "$HOME/.bashrc"; then
              echo "pyfony_env.sh was not added to .bashrc"
              exit 1
          fi
          if [[ ! -f "$HOME/pyfony_env.sh" ]]; then
              echo "pyfony_env.sh was not created"
              exit 1
          fi
        shell: sh {0}
  app-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'bricksflow/bricksflow'
          path: 'bricksflow'
      - name: Conda installation
        run: |
          powershell -Command "Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Windows-x86_64.exe -OutFile Miniconda3-latest-Windows-x86_64.exe"
          start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /AddToPath=1 /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
        shell: cmd
      - name: Init
        run: |
          echo "************ Setting up Conda ************"
          source ~/Miniconda3/etc/profile.d/conda.sh
          PATH=$HOME/Miniconda3/Scripts:$PATH
          echo "****** Setting up Conda environment ******"
          cd $APP_TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          echo "******* 2nd env-init.sh invocation *******"
          PATH=$HOME/.poetry/bin:$PATH
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          ./run_tests.sh
          echo "********* .bashrc modifications **********"
          if ! grep -q "pyfony_env.sh" "$HOME/.bashrc"; then
              echo "pyfony_env.sh was not added to .bashrc"
              exit 1
          fi
          if [[ ! -f "$HOME/pyfony_env.sh" ]]; then
              echo "pyfony_env.sh was not created"
              exit 1
          fi
        shell: sh {0}

  package-windows-condaNotOnPath:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'bricksflow/databricks-bundle'
          path: 'databricks-bundle'
      - name: Conda installation
        run: |
          powershell -Command "Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Windows-x86_64.exe -OutFile Miniconda3-latest-Windows-x86_64.exe"
          start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
        shell: cmd
      - name: Init
        run: |
          echo "************ Setting up Conda ************"
          source ~/Miniconda3/etc/profile.d/conda.sh
          echo "****** Setting up Conda environment ******"
          cd $PACKAGE_TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          echo "******* 2nd env-init.sh invocation *******"
          PATH=$HOME/.poetry/bin:$PATH
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          ./run_tests.sh
          echo "********* .bashrc modifications **********"
          if ! grep -q "pyfony_env.sh" "$HOME/.bashrc"; then
              echo "pyfony_env.sh was not added to .bashrc"
              exit 1
          fi
          if [[ ! -f "$HOME/pyfony_env.sh" ]]; then
              echo "pyfony_env.sh was not created"
              exit 1
          fi
        shell: sh {0}

  package-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'bricksflow/databricks-bundle'
          path: 'databricks-bundle'
      - name: Init
        run: |
          echo "************ Installing Conda ************"
          curl https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-MacOSX-x86_64.sh --silent -o Miniconda3-latest-MacOSX-x86_64.sh
          chmod +x Miniconda3-latest-MacOSX-x86_64.sh
          bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
          source ~/miniconda/etc/profile.d/conda.sh
          echo "****** Setting up Conda environment ******"
          cd $PACKAGE_TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          echo "******* 2nd env-init.sh invocation *******"
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          ./run_tests.sh
          echo "********* .bashrc modifications **********"
          if ! grep -q "pyfony_env.sh" "$HOME/.bashrc"; then
              echo "pyfony_env.sh was not added to .bashrc"
              exit 1
          fi
          if [[ ! -f "$HOME/pyfony_env.sh" ]]; then
              echo "pyfony_env.sh was not created"
              exit 1
          fi
  app-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'bricksflow/bricksflow'
          path: 'bricksflow'
      - name: Init
        run: |
          echo "************ Installing Conda ************"
          curl https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-MacOSX-x86_64.sh --silent -o Miniconda3-latest-MacOSX-x86_64.sh
          chmod +x Miniconda3-latest-MacOSX-x86_64.sh
          bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
          source ~/miniconda/etc/profile.d/conda.sh
          echo "****** Setting up Conda environment ******"
          cd $APP_TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          echo "******* 2nd env-init.sh invocation *******"
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          ./run_tests.sh
          echo "********* .bashrc modifications **********"
          if ! grep -q "pyfony_env.sh" "$HOME/.bashrc"; then
              echo "pyfony_env.sh was not added to .bashrc"
              exit 1
          fi
          if [[ ! -f "$HOME/pyfony_env.sh" ]]; then
              echo "pyfony_env.sh was not created"
              exit 1
          fi
